server:
  port: 10086
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:opengauss://120.46.144.9:26000/school
    username: test
    password: Shujuku813
    driver-class-name: org.opengauss.Driver

mybatis:
  mapper-locations: classpath*:com/project/mappers/*.xml
  type-aliases-package: com.project.entity.po

